name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  NU_VERSION: "0.108.0"

jobs:
  build:
    name: Build Release
    strategy:
      matrix:
        include:
          - host: windows-latest
            for: windows-x64
          - host: ubuntu-latest
            for: linux-x64

    runs-on: ${{ matrix.host }}

    env:
      ARTIFACT_NAME: nlwkn-toolset-${{ matrix.for }}.zip

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        run: rustup toolchain install

      - name: Use Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Release
        run: cargo build --release

      - name: Zip Binaries
        uses: vimtor/action-zip@v1.2
        with:
          dest: ${{ env.ARTIFACT_NAME }}
          files: >
            target/release/adapter
            target/release/adapter.exe
            target/release/exporter
            target/release/exporter.exe
            target/release/fetcher
            target/release/fetcher.exe
            target/release/parser
            target/release/parser.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Cargo.lock
        uses: actions/checkout@v4
        with:
          sparse-checkout: Cargo.lock
          sparse-checkout-cone-mode: false

      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist
          merge-multiple: true

      - name: Setup Nushell
        uses: hustcer/setup-nu@v3
        with:
          version: ${{ env.NU_VERSION }}

      - name: Get Version
        id: version
        shell: nu {0}
        run: |
          open Cargo.lock
          | from toml
          | get package
          | where name == "nlwkn"
          | get version.0
          | "version=" + $in
          | save $env.GITHUB_OUTPUT -ra

      - name: Draft Release
        run: gh release create "$TAG" dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: v${{ steps.version.outputs.version }}
